version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - misspell
    - gocritic
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-naming
      - name: var-naming
      - name: indent-error-flow
      - name: early-return

  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters: [gocritic, revive]
