---
# line-length
MD013:
  # Number of characters
  line_length: 256
  # Number of characters for headings
  heading_line_length: 79
  # Number of characters for code blocks
  code_block_line_length: 128
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
# no-duplicate-header
MD024:
  siblings_only: true
# ol-prefix
MD029:
  style: ordered
# no-inline-html
MD033:
  allowed_elements:
    - "details"
    - "summary"
