// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	UnixName    string             `json:"unix_name"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
