// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkProjectExistsByUnixName = `-- name: CheckProjectExistsByUnixName :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE unix_name = $1
)
`

func (q *Queries) CheckProjectExistsByUnixName(ctx context.Context, unixName string) (bool, error) {
	row := q.db.QueryRow(ctx, checkProjectExistsByUnixName, unixName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, name, unix_name, description, active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, unix_name, description, active, created_at, updated_at
`

type CreateProjectParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	UnixName    string             `json:"unix_name"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.UnixName,
		arg.Description,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnixName,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, name, unix_name, description, active, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnixName,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByUnixName = `-- name: GetProjectByUnixName :one
SELECT id, name, unix_name, description, active, created_at, updated_at
FROM projects
WHERE unix_name = $1
`

func (q *Queries) GetProjectByUnixName(ctx context.Context, unixName string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUnixName, unixName)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnixName,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, unix_name, description, active, created_at, updated_at
FROM projects
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnixName,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE(NULLIF($2, ''), name),
    description = COALESCE($4, description),
    active = COALESCE($5, active),
    updated_at = $3
WHERE id = $1
RETURNING id, name, unix_name, description, active, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID        `json:"id"`
	Column2     interface{}        `json:"column_2"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Description pgtype.Text        `json:"description"`
	Active      pgtype.Bool        `json:"active"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Column2,
		arg.UpdatedAt,
		arg.Description,
		arg.Active,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnixName,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
